### ISSUE TITLE
请问怎么分析本地镜像呢

### ISSUE THREAD

**Issue by Shimada666** [vicanso/diving-rs#2]
构建了本地镜像，打了 tag。但是使用 diving 进行分析时，仍然是在网络上进行拉取
```
➜  img ./diving flask:test
2023-03-28T16:21:44.440608Z  INFO diving::image::docker: Getting token url="https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/flask:pull"
2023-03-28T16:21:45.327551Z  INFO diving::image::docker: Got token url="https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/flask:pull"
2023-03-28T16:21:45.327604Z  INFO diving::image::docker: Getting manifest url="https://index.docker.io/v2/library/flask/manifests/test"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Docker { message: "authentication required", code: "UNAUTHORIZED", url: "https://index.docker.io/v2/library/flask/manifests/test" }', src/main.rs:93:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by vicanso** [comment]
因为不再直接依赖docker，因此只能通过网络的形式获取，需要先把镜像推送至镜像源(自建镜像源或docker等公开镜像源)

**Comment by vicanso** [comment]
@Shimada666 最新版本可以先导出镜像至本地再分析。

```bash
docker save redis:alpine > /tmp/redis.tar
diving file:///tmp/redis.tar
```

**Comment by Shimada666** [comment]
> @Shimada666 最新版本可以先导出镜像至本地再分析。
> 
> ```shell
> docker save redis:alpine > /tmp/redis.tar
> diving file:///tmp/redis.tar
> ```

web的方式可以支持吗

**Comment by vicanso** [comment]
可以的，镜像地址为`file:///tmp/redis.tar`即可，需要注意如果web是部署在服务器，那么redis.tar需要保存在服务器上

**Comment by yurenchen000** [comment]
How about add a wrapper for that,
and add `bash completion` support: https://github.com/wagoodman/dive/issues/239


> @Shimada666 最新版本可以先导出镜像至本地再分析。
> 
> ```shell
> docker save redis:alpine > /tmp/redis.tar
> diving file:///tmp/redis.tar
> ```

**Comment by vicanso** [comment]
This feature will be supported in next version.

**Comment by yurenchen000** [comment]
> 可以的，镜像地址为`file:///tmp/redis.tar`即可，需要注意如果web是部署在服务器，那么redis.tar需要保存在服务器上

when I run terminal mode, it's fine:
```sh
./diving   file:///tmp/test.tar
```

<br>

but when I run web mode by
```sh
./diving -m web file:///tmp/test.tar
# OR
./diving -m web
```

and input  `file:///tmp/test.tar` in web (with arm64 or amd64 selection), it not happy:

<br>

web page says: 
> Layer handle fail: Tar fail: No such file or directory (os error 2)

backend log: 
> INFO diving::middleware: traceId="V1zpjm" category="accessLog" ip="127.0.0.1" method="GET" uri="/api/analyze?image=file:///tmp/test.tar?arch=arm64" status=400 cost=0
> INFO diving::middleware: traceId="tNDEee" category="accessLog" ip="127.0.0.1" method="GET" uri="/api/analyze?image=file:///tmp/test.tar?arch=amd64" status=400 cost=0

<br>

it's `diving 0.4.15`

**Comment by vicanso** [comment]
The latest version support arch of image and default arch is amd64, so the path is wrong. I will fix it asap.

**Comment by vicanso** [comment]
@yurenchen000 @Shimada666 The latest support analyze local image:

```
diving docker://redis:alpine
```

**Comment by yurenchen000** [comment]
> @yurenchen000 @Shimada666 The latest support analyze local image:
> 
> ```
> diving docker://redis:alpine
> ```

Thanks for your efforts
It works! 

version `0.4.17`

in web or terminal mode, both works fine
- file:///tmp/test.tar
- docker://redis:alpine

<br>

maybe more friendly 
　if show image syntax TIPS in cli --help 
　or near web input box (or some type select button)
