### ISSUE TITLE
is it possible add ctrl+z for job control support 

### ISSUE THREAD

**Issue by yurenchen000** [vicanso/diving-rs#4]
same thing in `dive`
https://github.com/wagoodman/dive/issues/297

**Comment by vicanso** [comment]
I don't have a solution yet, I will support it when I find a solution.

**Comment by vicanso** [comment]
@yurenchen000 Please try the latest version.

**Comment by yurenchen000** [comment]
works perfectly! :sparkles: 
I don't have to exit and loading again and again.

appreciate it

:+1: :+1:
