### ISSUE TITLE
feat: How about specify listen addr other than `:7001` in web mode

### ISSUE THREAD

**Issue by yurenchen000** [vicanso/diving-rs#5]
seems listen addr `:7001` is hardcoded
 
// port 7001 not always availble on the server

https://github.com/vicanso/diving-rs/blob/v0.4.15/src/main.rs#L123

**Comment by vicanso** [comment]
@yurenchen000 The latest version supports it.
```bash
diving --mode web --listen 127.0.0.1:7001
```

**Comment by yurenchen000** [comment]
thank you
  version `0.4.17` works as expected :tada: 

<br>

It maybe more friendly for cli
If `--listen :7001` format is supported (allow omit default 0.0.0.0 ipaddr)

> $ ./diving_0.4.17 -m web --listen :7002 
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AddrParseError(Socket)', src/main.rs:126:40
