### ISSUE TITLE
crashed to analysic

### ISSUE THREAD

**Issue by mvpbang** [vicanso/diving-rs#6]
# cmd
./diving-linux-x86 file:///root/mysql.tar

# diving had a problem and crashed
name = "diving"
operating_system = "CentOS 7.0.0 [64-bit]"
crate_version = "0.5.0"
explanation = """
Panic occurred in file 'src/main.rs' at line 110
"""
cause = "called `Result::unwrap()` on an `Err` value: SerdeJson { source: Error(\"invalid type: null, expected a sequence\", line: 1, column: 98) }"
method = "Panic"
backtrace = """

   0: 0x7f610183c2c1 - <unresolved>
   1: 0x7f61019b914e - <unresolved>
   2: 0x7f61019d8f1b - <unresolved>
   3: 0x7f6101a0d903 - <unresolved>
   4: 0x7f61019d6873 - <unresolved>"""

**Comment by vicanso** [comment]
Please show me these:

1. The version of mysql image
2. The version of docker
3. mysql.tar is created by `docker save mysql > mysql.tar` ?

**Comment by vicanso** [comment]
I tried like this, it's ok. The script: 

```bash
docker save mysql > mysql.tar
./diving-linux-x86 file:///home/vicanso/tmp/mysql.tar
```

My docker version is: Docker version 20.10.16, build aa7e414

![demo](https://github.com/vicanso/diving-rs/assets/437351/b30a54ea-047f-48f4-ba57-0dc43c002fa0)
