### ISSUE TITLE
使用 docker 部署和运行时，能否直接获取 dockerd 宿主机上的镜像

### ISSUE THREAD

**Issue by xtay573269555** [vicanso/diving-rs#7]
您好，我使用以下命令部署的 docker 版本
```
docker run -d --restart unless-stopped \
  --name diving \
  --hostname diving \
  -p 0.0.0.0:7001:7001/tcp \
  vicanso/diving:0.6.4
```

默认情况下，这样部署之后是无法直接获取 dockerd 宿主机上的 docker 镜像。我尝试添加以下参数，将 docker.sock 传入 container 中，再测试 docker://redis:7.2.3-alpine 镜像还是无法正常执行。
```
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
```

是否有办法实现这种需求？

**Comment by vicanso** [comment]
diving docker://redis:alpine 此方式需要先安装了docker客户端，而默认的镜像是并未安排的。如果是本机开发生成的镜像，建议可直接使用diving执行文件，已编译支持各平台。如果的确需要使用此形式，那么可基于`vicanso/diving:0.6.4`镜像再创建新的镜像，新的镜像安装docker：

```bash
RUN apk update \
  && apk add docker
```

**Comment by xtay573269555** [comment]
好的，谢谢
